create table books (
	id bigint generated by default as identity,
	authors varchar(255) not null,
	isbn varchar(255) not null,
	name varchar(255) not null,
	price decimal(19,2) not null,
	published_on date not null,
	publisher varchar(255) not null,
	primary key (id)
);
    
create table customers (
	id bigint generated by default as identity,
	city varchar(60) not null,
	country_region varchar(55) not null,
	email varchar(254) not null,
	name varchar(50) not null,
	phone_number varchar(15) not null,
	postal_code varchar(18) not null,
	street_and_house_number varchar(100) not null,
	surname varchar(50) not null,
	primary key (id)
);
    
create table orders (
	id bigint generated by default as identity,
	order_date date not null,
	book_id bigint,
	customer_id bigint,
	primary key (id)
);

CREATE TABLE USERS (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	password VARCHAR(255) NOT NULL,
	enabled TINYINT(1) NOT NULL,
	PRIMARY KEY (username)
);

CREATE TABLE AUTHORITIES (
	username VARCHAR(255) NOT NULL,
	authority VARCHAR(255) NOT NULL
);